// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compatibility.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const decrementCompatibilityCredits = `-- name: DecrementCompatibilityCredits :exec
UPDATE compatibility_credits
SET remaining = remaining - 1, updated_at = NOW()
WHERE user_id = $1 AND remaining > 0
`

func (q *Queries) DecrementCompatibilityCredits(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, decrementCompatibilityCredits, userID)
	return err
}

const getCompatibilityCard = `-- name: GetCompatibilityCard :one
SELECT id, user_id, other_birth_date, other_birth_time, other_birth_place, other_gender, include_love, title, compatibility_score, compatibility_label, result, created_at FROM compatibility_cards
WHERE user_id = $1 AND id = $2
`

type GetCompatibilityCardParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetCompatibilityCard(ctx context.Context, arg GetCompatibilityCardParams) (CompatibilityCard, error) {
	row := q.db.QueryRow(ctx, getCompatibilityCard, arg.UserID, arg.ID)
	var i CompatibilityCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtherBirthDate,
		&i.OtherBirthTime,
		&i.OtherBirthPlace,
		&i.OtherGender,
		&i.IncludeLove,
		&i.Title,
		&i.CompatibilityScore,
		&i.CompatibilityLabel,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const getCompatibilityCredits = `-- name: GetCompatibilityCredits :one
SELECT remaining, period_start, updated_at
FROM compatibility_credits
WHERE user_id = $1
`

type GetCompatibilityCreditsRow struct {
	Remaining   int32     `json:"remaining"`
	PeriodStart time.Time `json:"period_start"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetCompatibilityCredits(ctx context.Context, userID int64) (GetCompatibilityCreditsRow, error) {
	row := q.db.QueryRow(ctx, getCompatibilityCredits, userID)
	var i GetCompatibilityCreditsRow
	err := row.Scan(&i.Remaining, &i.PeriodStart, &i.UpdatedAt)
	return i, err
}

const insertCompatibilityCard = `-- name: InsertCompatibilityCard :one
INSERT INTO compatibility_cards (
    user_id, other_birth_date, other_birth_time, other_birth_place,
    other_gender, include_love, title, compatibility_score,
    compatibility_label, result
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, other_birth_date, other_birth_time, other_birth_place, other_gender, include_love, title, compatibility_score, compatibility_label, result, created_at
`

type InsertCompatibilityCardParams struct {
	UserID             int64           `json:"user_id"`
	OtherBirthDate     time.Time       `json:"other_birth_date"`
	OtherBirthTime     *string         `json:"other_birth_time"`
	OtherBirthPlace    *string         `json:"other_birth_place"`
	OtherGender        string          `json:"other_gender"`
	IncludeLove        bool            `json:"include_love"`
	Title              *string         `json:"title"`
	CompatibilityScore *int32          `json:"compatibility_score"`
	CompatibilityLabel *string         `json:"compatibility_label"`
	Result             json.RawMessage `json:"result"`
}

func (q *Queries) InsertCompatibilityCard(ctx context.Context, arg InsertCompatibilityCardParams) (CompatibilityCard, error) {
	row := q.db.QueryRow(ctx, insertCompatibilityCard,
		arg.UserID,
		arg.OtherBirthDate,
		arg.OtherBirthTime,
		arg.OtherBirthPlace,
		arg.OtherGender,
		arg.IncludeLove,
		arg.Title,
		arg.CompatibilityScore,
		arg.CompatibilityLabel,
		arg.Result,
	)
	var i CompatibilityCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtherBirthDate,
		&i.OtherBirthTime,
		&i.OtherBirthPlace,
		&i.OtherGender,
		&i.IncludeLove,
		&i.Title,
		&i.CompatibilityScore,
		&i.CompatibilityLabel,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const insertCompatibilityCredits = `-- name: InsertCompatibilityCredits :exec
INSERT INTO compatibility_credits (user_id, remaining, period_start)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
`

type InsertCompatibilityCreditsParams struct {
	UserID      int64     `json:"user_id"`
	Remaining   int32     `json:"remaining"`
	PeriodStart time.Time `json:"period_start"`
}

func (q *Queries) InsertCompatibilityCredits(ctx context.Context, arg InsertCompatibilityCreditsParams) error {
	_, err := q.db.Exec(ctx, insertCompatibilityCredits, arg.UserID, arg.Remaining, arg.PeriodStart)
	return err
}

const listCompatibilityCards = `-- name: ListCompatibilityCards :many
SELECT id, other_birth_date, other_birth_time, other_birth_place,
       other_gender, include_love, title, compatibility_score,
       compatibility_label, created_at
FROM compatibility_cards
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListCompatibilityCardsParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type ListCompatibilityCardsRow struct {
	ID                 int64     `json:"id"`
	OtherBirthDate     time.Time `json:"other_birth_date"`
	OtherBirthTime     *string   `json:"other_birth_time"`
	OtherBirthPlace    *string   `json:"other_birth_place"`
	OtherGender        string    `json:"other_gender"`
	IncludeLove        bool      `json:"include_love"`
	Title              *string   `json:"title"`
	CompatibilityScore *int32    `json:"compatibility_score"`
	CompatibilityLabel *string   `json:"compatibility_label"`
	CreatedAt          time.Time `json:"created_at"`
}

func (q *Queries) ListCompatibilityCards(ctx context.Context, arg ListCompatibilityCardsParams) ([]ListCompatibilityCardsRow, error) {
	rows, err := q.db.Query(ctx, listCompatibilityCards, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompatibilityCardsRow
	for rows.Next() {
		var i ListCompatibilityCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.OtherBirthDate,
			&i.OtherBirthTime,
			&i.OtherBirthPlace,
			&i.OtherGender,
			&i.IncludeLove,
			&i.Title,
			&i.CompatibilityScore,
			&i.CompatibilityLabel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshCompatibilityCredits = `-- name: RefreshCompatibilityCredits :exec
UPDATE compatibility_credits
SET remaining = $2, period_start = $3, updated_at = NOW()
WHERE user_id = $1
`

type RefreshCompatibilityCreditsParams struct {
	UserID      int64     `json:"user_id"`
	Remaining   int32     `json:"remaining"`
	PeriodStart time.Time `json:"period_start"`
}

func (q *Queries) RefreshCompatibilityCredits(ctx context.Context, arg RefreshCompatibilityCreditsParams) error {
	_, err := q.db.Exec(ctx, refreshCompatibilityCredits, arg.UserID, arg.Remaining, arg.PeriodStart)
	return err
}
