// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const getDailyContentByDate = `-- name: GetDailyContentByDate :one
SELECT id, date, moon_phase, moon_sign, content, generated_at FROM daily_content WHERE date = $1
`

func (q *Queries) GetDailyContentByDate(ctx context.Context, date time.Time) (DailyContent, error) {
	row := q.db.QueryRow(ctx, getDailyContentByDate, date)
	var i DailyContent
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.MoonPhase,
		&i.MoonSign,
		&i.Content,
		&i.GeneratedAt,
	)
	return i, err
}

const upsertDailyContent = `-- name: UpsertDailyContent :exec
INSERT INTO daily_content (date, moon_phase, moon_sign, content)
VALUES ($1, $2, $3, $4)
ON CONFLICT (date) DO UPDATE SET
    moon_phase   = EXCLUDED.moon_phase,
    moon_sign    = EXCLUDED.moon_sign,
    content      = EXCLUDED.content,
    generated_at = NOW()
`

type UpsertDailyContentParams struct {
	Date      time.Time       `json:"date"`
	MoonPhase string          `json:"moon_phase"`
	MoonSign  string          `json:"moon_sign"`
	Content   json.RawMessage `json:"content"`
}

func (q *Queries) UpsertDailyContent(ctx context.Context, arg UpsertDailyContentParams) error {
	_, err := q.db.Exec(ctx, upsertDailyContent,
		arg.Date,
		arg.MoonPhase,
		arg.MoonSign,
		arg.Content,
	)
	return err
}
