package db

import (
	"errors"

	"github.com/jackc/pgx/v5"
)

// IsNotFound reports whether err indicates the query returned no rows.
// Hand-written: not regenerated by `sqlc generate`.
func IsNotFound(err error) bool {
	return errors.Is(err, pgx.ErrNoRows)
}
