// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type CompatibilityCard struct {
	ID                 int64           `json:"id"`
	UserID             int64           `json:"user_id"`
	OtherBirthDate     time.Time       `json:"other_birth_date"`
	OtherBirthTime     *string         `json:"other_birth_time"`
	OtherBirthPlace    *string         `json:"other_birth_place"`
	OtherGender        string          `json:"other_gender"`
	IncludeLove        bool            `json:"include_love"`
	Title              *string         `json:"title"`
	CompatibilityScore *int32          `json:"compatibility_score"`
	CompatibilityLabel *string         `json:"compatibility_label"`
	Result             json.RawMessage `json:"result"`
	CreatedAt          time.Time       `json:"created_at"`
}

type CompatibilityCredit struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Remaining   int32     `json:"remaining"`
	PeriodStart time.Time `json:"period_start"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type DailyContent struct {
	ID          int64           `json:"id"`
	Date        time.Time       `json:"date"`
	MoonPhase   string          `json:"moon_phase"`
	MoonSign    string          `json:"moon_sign"`
	Content     json.RawMessage `json:"content"`
	GeneratedAt time.Time       `json:"generated_at"`
}

type NatalChart struct {
	ID              int64           `json:"id"`
	UserID          int64           `json:"user_id"`
	Planets         json.RawMessage `json:"planets"`
	HouseCusps      json.RawMessage `json:"house_cusps"`
	AscendantSign   string          `json:"ascendant_sign"`
	AscendantDegree float64         `json:"ascendant_degree"`
	Aspects         json.RawMessage `json:"aspects"`
	AspectPatterns  json.RawMessage `json:"aspect_patterns"`
	ChartShape      string          `json:"chart_shape"`
	SvgDark         string          `json:"svg_dark"`
	Portrait        string          `json:"portrait"`
	PortraitStatus  string          `json:"portrait_status"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	Summary         string          `json:"summary"`
}

type PaymentCharge struct {
	InvID     int64     `json:"inv_id"`
	UserID    int64     `json:"user_id"`
	Amount    int32     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type RecurringConsent struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Product     string    `json:"product"`
	OfferUrl    string    `json:"offer_url"`
	ConsentedAt time.Time `json:"consented_at"`
}

type Subscription struct {
	ID              int64      `json:"id"`
	UserID          int64      `json:"user_id"`
	Type            string     `json:"type"`
	Amount          int32      `json:"amount"`
	Status          string     `json:"status"`
	ProviderOrderID *string    `json:"provider_order_id"`
	CreatedAt       time.Time  `json:"created_at"`
	PaidAt          *time.Time `json:"paid_at"`
}

type User struct {
	ID              int64           `json:"id"`
	TelegramUserID  int64           `json:"telegram_user_id"`
	Username        *string         `json:"username"`
	DisplayName     *string         `json:"display_name"`
	BirthDate       time.Time       `json:"birth_date"`
	BirthTime       *string         `json:"birth_time"`
	BirthPlace      string          `json:"birth_place"`
	BirthLat        float64         `json:"birth_lat"`
	BirthLon        float64         `json:"birth_lon"`
	BirthTzone      float64         `json:"birth_tzone"`
	Gender          *string         `json:"gender"`
	Style           string          `json:"style"`
	Focus           string          `json:"focus"`
	Personalization json.RawMessage `json:"personalization"`
	ProStatus       string          `json:"pro_status"`
	ProActivatedAt  *time.Time      `json:"pro_activated_at"`
	TrialEndsAt     *time.Time      `json:"trial_ends_at"`
	SubEndsAt       *time.Time      `json:"sub_ends_at"`
	PushEnabled     bool            `json:"push_enabled"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type VoidCredit struct {
	ID          int64     `json:"id"`
	UserID      int64     `json:"user_id"`
	Remaining   int32     `json:"remaining"`
	PeriodStart time.Time `json:"period_start"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type VoidHistory struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Question  string    `json:"question"`
	Answer    string    `json:"answer"`
	CreatedAt time.Time `json:"created_at"`
}
