// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: natal.sql

package db

import (
	"context"
	"encoding/json"
)

const getNatalChartByUserID = `-- name: GetNatalChartByUserID :one
SELECT id, user_id, planets, house_cusps, ascendant_sign, ascendant_degree, aspects, aspect_patterns, chart_shape, svg_dark, portrait, portrait_status, created_at, updated_at, summary FROM natal_charts WHERE user_id = $1
`

func (q *Queries) GetNatalChartByUserID(ctx context.Context, userID int64) (NatalChart, error) {
	row := q.db.QueryRow(ctx, getNatalChartByUserID, userID)
	var i NatalChart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Planets,
		&i.HouseCusps,
		&i.AscendantSign,
		&i.AscendantDegree,
		&i.Aspects,
		&i.AspectPatterns,
		&i.ChartShape,
		&i.SvgDark,
		&i.Portrait,
		&i.PortraitStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
	)
	return i, err
}

const updateNatalChartPortrait = `-- name: UpdateNatalChartPortrait :exec
UPDATE natal_charts
SET portrait = $2, portrait_status = $3, updated_at = NOW()
WHERE user_id = $1
`

type UpdateNatalChartPortraitParams struct {
	UserID         int64  `json:"user_id"`
	Portrait       string `json:"portrait"`
	PortraitStatus string `json:"portrait_status"`
}

func (q *Queries) UpdateNatalChartPortrait(ctx context.Context, arg UpdateNatalChartPortraitParams) error {
	_, err := q.db.Exec(ctx, updateNatalChartPortrait, arg.UserID, arg.Portrait, arg.PortraitStatus)
	return err
}

const updateNatalChartSVG = `-- name: UpdateNatalChartSVG :exec
UPDATE natal_charts
SET svg_dark = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateNatalChartSVGParams struct {
	UserID  int64  `json:"user_id"`
	SvgDark string `json:"svg_dark"`
}

func (q *Queries) UpdateNatalChartSVG(ctx context.Context, arg UpdateNatalChartSVGParams) error {
	_, err := q.db.Exec(ctx, updateNatalChartSVG, arg.UserID, arg.SvgDark)
	return err
}

const upsertNatalChart = `-- name: UpsertNatalChart :one
INSERT INTO natal_charts (
    user_id, planets, house_cusps,
    ascendant_sign, ascendant_degree,
    aspects, aspect_patterns, chart_shape, svg_dark, portrait_status, summary
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (user_id) DO UPDATE SET
    planets          = EXCLUDED.planets,
    house_cusps      = EXCLUDED.house_cusps,
    ascendant_sign   = EXCLUDED.ascendant_sign,
    ascendant_degree = EXCLUDED.ascendant_degree,
    aspects          = EXCLUDED.aspects,
    aspect_patterns  = EXCLUDED.aspect_patterns,
    chart_shape      = EXCLUDED.chart_shape,
    svg_dark         = EXCLUDED.svg_dark,
    portrait_status  = EXCLUDED.portrait_status,
    summary          = EXCLUDED.summary,
    updated_at       = NOW()
RETURNING id, user_id, planets, house_cusps, ascendant_sign, ascendant_degree, aspects, aspect_patterns, chart_shape, svg_dark, portrait, portrait_status, created_at, updated_at, summary
`

type UpsertNatalChartParams struct {
	UserID          int64           `json:"user_id"`
	Planets         json.RawMessage `json:"planets"`
	HouseCusps      json.RawMessage `json:"house_cusps"`
	AscendantSign   string          `json:"ascendant_sign"`
	AscendantDegree float64         `json:"ascendant_degree"`
	Aspects         json.RawMessage `json:"aspects"`
	AspectPatterns  json.RawMessage `json:"aspect_patterns"`
	ChartShape      string          `json:"chart_shape"`
	SvgDark         string          `json:"svg_dark"`
	PortraitStatus  string          `json:"portrait_status"`
	Summary         string          `json:"summary"`
}

func (q *Queries) UpsertNatalChart(ctx context.Context, arg UpsertNatalChartParams) (NatalChart, error) {
	row := q.db.QueryRow(ctx, upsertNatalChart,
		arg.UserID,
		arg.Planets,
		arg.HouseCusps,
		arg.AscendantSign,
		arg.AscendantDegree,
		arg.Aspects,
		arg.AspectPatterns,
		arg.ChartShape,
		arg.SvgDark,
		arg.PortraitStatus,
		arg.Summary,
	)
	var i NatalChart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Planets,
		&i.HouseCusps,
		&i.AscendantSign,
		&i.AscendantDegree,
		&i.Aspects,
		&i.AspectPatterns,
		&i.ChartShape,
		&i.SvgDark,
		&i.Portrait,
		&i.PortraitStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Summary,
	)
	return i, err
}
