// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, type, amount)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateSubscriptionParams struct {
	UserID int64  `json:"user_id"`
	Type   string `json:"type"`
	Amount int32  `json:"amount"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.Type, arg.Amount)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, type, amount, status, provider_order_id, created_at, paid_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Status,
		&i.ProviderOrderID,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const markSubscriptionPaid = `-- name: MarkSubscriptionPaid :exec
UPDATE subscriptions
SET status = 'paid', paid_at = NOW(), provider_order_id = $2
WHERE id = $1 AND status <> 'paid'
`

type MarkSubscriptionPaidParams struct {
	ID              int64   `json:"id"`
	ProviderOrderID *string `json:"provider_order_id"`
}

func (q *Queries) MarkSubscriptionPaid(ctx context.Context, arg MarkSubscriptionPaidParams) error {
	_, err := q.db.Exec(ctx, markSubscriptionPaid, arg.ID, arg.ProviderOrderID)
	return err
}

const recordCharge = `-- name: RecordCharge :execrows
INSERT INTO payment_charges (inv_id, user_id, amount)
VALUES ($1, $2, $3)
ON CONFLICT (inv_id) DO NOTHING
`

type RecordChargeParams struct {
	InvID  int64 `json:"inv_id"`
	UserID int64 `json:"user_id"`
	Amount int32 `json:"amount"`
}

// Returns 1 when this InvId is new (apply PRO), 0 when it's a duplicate delivery.
func (q *Queries) RecordCharge(ctx context.Context, arg RecordChargeParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordCharge, arg.InvID, arg.UserID, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordConsent = `-- name: RecordConsent :exec
INSERT INTO recurring_consents (user_id, product, offer_url)
VALUES ($1, $2, $3)
`

type RecordConsentParams struct {
	UserID   int64  `json:"user_id"`
	Product  string `json:"product"`
	OfferUrl string `json:"offer_url"`
}

func (q *Queries) RecordConsent(ctx context.Context, arg RecordConsentParams) error {
	_, err := q.db.Exec(ctx, recordConsent, arg.UserID, arg.Product, arg.OfferUrl)
	return err
}
