// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
	"time"
)

const advanceRecurringSubscription = `-- name: AdvanceRecurringSubscription :exec
UPDATE recurring_subscriptions
SET next_charge_at = $2, failed_attempts = 0, last_attempt_at = NOW(), updated_at = NOW()
WHERE id = $1
`

type AdvanceRecurringSubscriptionParams struct {
	ID           int64     `json:"id"`
	NextChargeAt time.Time `json:"next_charge_at"`
}

func (q *Queries) AdvanceRecurringSubscription(ctx context.Context, arg AdvanceRecurringSubscriptionParams) error {
	_, err := q.db.Exec(ctx, advanceRecurringSubscription, arg.ID, arg.NextChargeAt)
	return err
}

const cancelRecurringByUser = `-- name: CancelRecurringByUser :exec
UPDATE recurring_subscriptions SET status = 'cancelled', updated_at = NOW()
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CancelRecurringByUser(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, cancelRecurringByUser, userID)
	return err
}

const cancelRecurringSubscription = `-- name: CancelRecurringSubscription :exec
UPDATE recurring_subscriptions SET status = 'cancelled', updated_at = NOW() WHERE id = $1
`

func (q *Queries) CancelRecurringSubscription(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, cancelRecurringSubscription, id)
	return err
}

const createRecurringSubscription = `-- name: CreateRecurringSubscription :exec
INSERT INTO recurring_subscriptions (user_id, mother_inv_id, amount, next_charge_at)
VALUES ($1, $2, $3, $4)
`

type CreateRecurringSubscriptionParams struct {
	UserID       int64     `json:"user_id"`
	MotherInvID  int64     `json:"mother_inv_id"`
	Amount       int32     `json:"amount"`
	NextChargeAt time.Time `json:"next_charge_at"`
}

func (q *Queries) CreateRecurringSubscription(ctx context.Context, arg CreateRecurringSubscriptionParams) error {
	_, err := q.db.Exec(ctx, createRecurringSubscription,
		arg.UserID,
		arg.MotherInvID,
		arg.Amount,
		arg.NextChargeAt,
	)
	return err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, type, amount)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateSubscriptionParams struct {
	UserID int64  `json:"user_id"`
	Type   string `json:"type"`
	Amount int32  `json:"amount"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.Type, arg.Amount)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActiveRecurringByUser = `-- name: GetActiveRecurringByUser :one
SELECT id, user_id, mother_inv_id, amount, status, next_charge_at, last_attempt_at, failed_attempts, created_at, updated_at FROM recurring_subscriptions WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) GetActiveRecurringByUser(ctx context.Context, userID int64) (RecurringSubscription, error) {
	row := q.db.QueryRow(ctx, getActiveRecurringByUser, userID)
	var i RecurringSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MotherInvID,
		&i.Amount,
		&i.Status,
		&i.NextChargeAt,
		&i.LastAttemptAt,
		&i.FailedAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, type, amount, status, provider_order_id, created_at, paid_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Status,
		&i.ProviderOrderID,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const listDueRecurring = `-- name: ListDueRecurring :many
SELECT id, user_id, mother_inv_id, amount, status, next_charge_at, last_attempt_at, failed_attempts, created_at, updated_at FROM recurring_subscriptions
WHERE status = 'active' AND next_charge_at <= NOW()
  AND (last_attempt_at IS NULL OR last_attempt_at < NOW() - INTERVAL '23 hours')
`

func (q *Queries) ListDueRecurring(ctx context.Context) ([]RecurringSubscription, error) {
	rows, err := q.db.Query(ctx, listDueRecurring)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringSubscription
	for rows.Next() {
		var i RecurringSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MotherInvID,
			&i.Amount,
			&i.Status,
			&i.NextChargeAt,
			&i.LastAttemptAt,
			&i.FailedAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecurringAttempt = `-- name: MarkRecurringAttempt :exec
UPDATE recurring_subscriptions
SET last_attempt_at = NOW(), failed_attempts = failed_attempts + 1, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkRecurringAttempt(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRecurringAttempt, id)
	return err
}

const markSubscriptionPaid = `-- name: MarkSubscriptionPaid :exec
UPDATE subscriptions
SET status = 'paid', paid_at = NOW(), provider_order_id = $2
WHERE id = $1 AND status <> 'paid'
`

type MarkSubscriptionPaidParams struct {
	ID              int64   `json:"id"`
	ProviderOrderID *string `json:"provider_order_id"`
}

func (q *Queries) MarkSubscriptionPaid(ctx context.Context, arg MarkSubscriptionPaidParams) error {
	_, err := q.db.Exec(ctx, markSubscriptionPaid, arg.ID, arg.ProviderOrderID)
	return err
}

const recordCharge = `-- name: RecordCharge :execrows
INSERT INTO payment_charges (inv_id, user_id, amount)
VALUES ($1, $2, $3)
ON CONFLICT (inv_id) DO NOTHING
`

type RecordChargeParams struct {
	InvID  int64 `json:"inv_id"`
	UserID int64 `json:"user_id"`
	Amount int32 `json:"amount"`
}

// Returns 1 when this InvId is new (apply PRO), 0 when it's a duplicate delivery.
func (q *Queries) RecordCharge(ctx context.Context, arg RecordChargeParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordCharge, arg.InvID, arg.UserID, arg.Amount)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordConsent = `-- name: RecordConsent :exec
INSERT INTO recurring_consents (user_id, product, offer_url)
VALUES ($1, $2, $3)
`

type RecordConsentParams struct {
	UserID   int64  `json:"user_id"`
	Product  string `json:"product"`
	OfferUrl string `json:"offer_url"`
}

func (q *Queries) RecordConsent(ctx context.Context, arg RecordConsentParams) error {
	_, err := q.db.Exec(ctx, recordConsent, arg.UserID, arg.Product, arg.OfferUrl)
	return err
}
