// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, type, amount)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateSubscriptionParams struct {
	UserID int64  `json:"user_id"`
	Type   string `json:"type"`
	Amount int32  `json:"amount"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSubscription, arg.UserID, arg.Type, arg.Amount)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, type, amount, status, provider_order_id, created_at, paid_at FROM subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Amount,
		&i.Status,
		&i.ProviderOrderID,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const markSubscriptionPaid = `-- name: MarkSubscriptionPaid :exec
UPDATE subscriptions
SET status = 'paid', paid_at = NOW(), provider_order_id = $2
WHERE id = $1 AND status <> 'paid'
`

type MarkSubscriptionPaidParams struct {
	ID              int64   `json:"id"`
	ProviderOrderID *string `json:"provider_order_id"`
}

func (q *Queries) MarkSubscriptionPaid(ctx context.Context, arg MarkSubscriptionPaidParams) error {
	_, err := q.db.Exec(ctx, markSubscriptionPaid, arg.ID, arg.ProviderOrderID)
	return err
}
