// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"
)

type Querier interface {
	ActivatePro(ctx context.Context, id int64) (User, error)
	AdvanceRecurringSubscription(ctx context.Context, arg AdvanceRecurringSubscriptionParams) error
	CancelPro(ctx context.Context, id int64) error
	CancelRecurringByUser(ctx context.Context, userID int64) error
	CancelRecurringSubscription(ctx context.Context, id int64) error
	CreateRecurringSubscription(ctx context.Context, arg CreateRecurringSubscriptionParams) error
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (int64, error)
	DecrementCompatibilityCredits(ctx context.Context, userID int64) error
	DecrementVoidCredits(ctx context.Context, userID int64) error
	DeleteVoidEntry(ctx context.Context, arg DeleteVoidEntryParams) error
	GetActiveRecurringByUser(ctx context.Context, userID int64) (RecurringSubscription, error)
	GetCompatibilityCard(ctx context.Context, arg GetCompatibilityCardParams) (CompatibilityCard, error)
	GetCompatibilityCredits(ctx context.Context, userID int64) (GetCompatibilityCreditsRow, error)
	GetDailyContentByDate(ctx context.Context, date time.Time) (DailyContent, error)
	GetNatalChartByUserID(ctx context.Context, userID int64) (NatalChart, error)
	GetSubscriptionByID(ctx context.Context, id int64) (Subscription, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByTelegramUserID(ctx context.Context, telegramUserID int64) (User, error)
	GetVoidCredits(ctx context.Context, userID int64) (GetVoidCreditsRow, error)
	GetVoidEntry(ctx context.Context, arg GetVoidEntryParams) (VoidHistory, error)
	InsertCompatibilityCard(ctx context.Context, arg InsertCompatibilityCardParams) (CompatibilityCard, error)
	InsertCompatibilityCredits(ctx context.Context, arg InsertCompatibilityCreditsParams) error
	InsertVoidCredits(ctx context.Context, arg InsertVoidCreditsParams) error
	InsertVoidEntry(ctx context.Context, arg InsertVoidEntryParams) (VoidHistory, error)
	ListCompatibilityCards(ctx context.Context, arg ListCompatibilityCardsParams) ([]ListCompatibilityCardsRow, error)
	ListDueRecurring(ctx context.Context) ([]RecurringSubscription, error)
	ListPushEnabledUsers(ctx context.Context) ([]User, error)
	ListVoidHistory(ctx context.Context, arg ListVoidHistoryParams) ([]VoidHistory, error)
	MarkRecurringAttempt(ctx context.Context, id int64) error
	MarkSubscriptionPaid(ctx context.Context, arg MarkSubscriptionPaidParams) error
	// Returns 1 when this InvId is new (apply PRO), 0 when it's a duplicate delivery.
	RecordCharge(ctx context.Context, arg RecordChargeParams) (int64, error)
	RecordConsent(ctx context.Context, arg RecordConsentParams) error
	RefreshCompatibilityCredits(ctx context.Context, arg RefreshCompatibilityCreditsParams) error
	RefreshVoidCredits(ctx context.Context, arg RefreshVoidCreditsParams) error
	UpdateNatalChartPortrait(ctx context.Context, arg UpdateNatalChartPortraitParams) error
	UpdateNatalChartSVG(ctx context.Context, arg UpdateNatalChartSVGParams) error
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error
	UpdateUserFocus(ctx context.Context, arg UpdateUserFocusParams) error
	UpdateUserPersonalization(ctx context.Context, arg UpdateUserPersonalizationParams) error
	UpdateUserProStatus(ctx context.Context, arg UpdateUserProStatusParams) error
	UpdateUserPushEnabled(ctx context.Context, arg UpdateUserPushEnabledParams) error
	UpdateUserStyle(ctx context.Context, arg UpdateUserStyleParams) error
	UpsertDailyContent(ctx context.Context, arg UpsertDailyContentParams) error
	UpsertNatalChart(ctx context.Context, arg UpsertNatalChartParams) (NatalChart, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
