// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const activatePro = `-- name: ActivatePro :one
UPDATE users
SET pro_status = 'active',
    pro_activated_at = NOW(),
    sub_ends_at = NOW() + INTERVAL '30 days',
    updated_at = NOW()
WHERE id = $1
RETURNING id, telegram_user_id, username, display_name, birth_date, birth_time, birth_place, birth_lat, birth_lon, birth_tzone, gender, style, focus, personalization, pro_status, pro_activated_at, trial_ends_at, sub_ends_at, push_enabled, created_at, updated_at
`

func (q *Queries) ActivatePro(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, activatePro, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.Username,
		&i.DisplayName,
		&i.BirthDate,
		&i.BirthTime,
		&i.BirthPlace,
		&i.BirthLat,
		&i.BirthLon,
		&i.BirthTzone,
		&i.Gender,
		&i.Style,
		&i.Focus,
		&i.Personalization,
		&i.ProStatus,
		&i.ProActivatedAt,
		&i.TrialEndsAt,
		&i.SubEndsAt,
		&i.PushEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelPro = `-- name: CancelPro :exec
UPDATE users
SET pro_status = 'free', sub_ends_at = NULL, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelPro(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, cancelPro, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, telegram_user_id, username, display_name, birth_date, birth_time, birth_place, birth_lat, birth_lon, birth_tzone, gender, style, focus, personalization, pro_status, pro_activated_at, trial_ends_at, sub_ends_at, push_enabled, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.Username,
		&i.DisplayName,
		&i.BirthDate,
		&i.BirthTime,
		&i.BirthPlace,
		&i.BirthLat,
		&i.BirthLon,
		&i.BirthTzone,
		&i.Gender,
		&i.Style,
		&i.Focus,
		&i.Personalization,
		&i.ProStatus,
		&i.ProActivatedAt,
		&i.TrialEndsAt,
		&i.SubEndsAt,
		&i.PushEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTelegramUserID = `-- name: GetUserByTelegramUserID :one
SELECT id, telegram_user_id, username, display_name, birth_date, birth_time, birth_place, birth_lat, birth_lon, birth_tzone, gender, style, focus, personalization, pro_status, pro_activated_at, trial_ends_at, sub_ends_at, push_enabled, created_at, updated_at FROM users WHERE telegram_user_id = $1
`

func (q *Queries) GetUserByTelegramUserID(ctx context.Context, telegramUserID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramUserID, telegramUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.Username,
		&i.DisplayName,
		&i.BirthDate,
		&i.BirthTime,
		&i.BirthPlace,
		&i.BirthLat,
		&i.BirthLon,
		&i.BirthTzone,
		&i.Gender,
		&i.Style,
		&i.Focus,
		&i.Personalization,
		&i.ProStatus,
		&i.ProActivatedAt,
		&i.TrialEndsAt,
		&i.SubEndsAt,
		&i.PushEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPushEnabledUsers = `-- name: ListPushEnabledUsers :many
SELECT id, telegram_user_id, username, display_name, birth_date, birth_time, birth_place, birth_lat, birth_lon, birth_tzone, gender, style, focus, personalization, pro_status, pro_activated_at, trial_ends_at, sub_ends_at, push_enabled, created_at, updated_at FROM users WHERE push_enabled = true
`

func (q *Queries) ListPushEnabledUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listPushEnabledUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TelegramUserID,
			&i.Username,
			&i.DisplayName,
			&i.BirthDate,
			&i.BirthTime,
			&i.BirthPlace,
			&i.BirthLat,
			&i.BirthLon,
			&i.BirthTzone,
			&i.Gender,
			&i.Style,
			&i.Focus,
			&i.Personalization,
			&i.ProStatus,
			&i.ProActivatedAt,
			&i.TrialEndsAt,
			&i.SubEndsAt,
			&i.PushEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDisplayName = `-- name: UpdateUserDisplayName :exec
UPDATE users SET display_name = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserDisplayNameParams struct {
	ID          int64   `json:"id"`
	DisplayName *string `json:"display_name"`
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	return err
}

const updateUserFocus = `-- name: UpdateUserFocus :exec
UPDATE users SET focus = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserFocusParams struct {
	ID    int64  `json:"id"`
	Focus string `json:"focus"`
}

func (q *Queries) UpdateUserFocus(ctx context.Context, arg UpdateUserFocusParams) error {
	_, err := q.db.Exec(ctx, updateUserFocus, arg.ID, arg.Focus)
	return err
}

const updateUserPersonalization = `-- name: UpdateUserPersonalization :exec
UPDATE users SET personalization = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPersonalizationParams struct {
	ID              int64           `json:"id"`
	Personalization json.RawMessage `json:"personalization"`
}

func (q *Queries) UpdateUserPersonalization(ctx context.Context, arg UpdateUserPersonalizationParams) error {
	_, err := q.db.Exec(ctx, updateUserPersonalization, arg.ID, arg.Personalization)
	return err
}

const updateUserProStatus = `-- name: UpdateUserProStatus :exec
UPDATE users SET pro_status = $2, sub_ends_at = $3, updated_at = NOW() WHERE id = $1
`

type UpdateUserProStatusParams struct {
	ID        int64      `json:"id"`
	ProStatus string     `json:"pro_status"`
	SubEndsAt *time.Time `json:"sub_ends_at"`
}

func (q *Queries) UpdateUserProStatus(ctx context.Context, arg UpdateUserProStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserProStatus, arg.ID, arg.ProStatus, arg.SubEndsAt)
	return err
}

const updateUserPushEnabled = `-- name: UpdateUserPushEnabled :exec
UPDATE users SET push_enabled = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserPushEnabledParams struct {
	ID          int64 `json:"id"`
	PushEnabled bool  `json:"push_enabled"`
}

func (q *Queries) UpdateUserPushEnabled(ctx context.Context, arg UpdateUserPushEnabledParams) error {
	_, err := q.db.Exec(ctx, updateUserPushEnabled, arg.ID, arg.PushEnabled)
	return err
}

const updateUserStyle = `-- name: UpdateUserStyle :exec
UPDATE users SET style = $2, updated_at = NOW() WHERE id = $1
`

type UpdateUserStyleParams struct {
	ID    int64  `json:"id"`
	Style string `json:"style"`
}

func (q *Queries) UpdateUserStyle(ctx context.Context, arg UpdateUserStyleParams) error {
	_, err := q.db.Exec(ctx, updateUserStyle, arg.ID, arg.Style)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    telegram_user_id, username, display_name,
    birth_date, birth_time, birth_place,
    birth_lat, birth_lon, birth_tzone, gender,
    style, focus, personalization
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (telegram_user_id) DO UPDATE SET
    username        = EXCLUDED.username,
    display_name    = EXCLUDED.display_name,
    birth_date      = EXCLUDED.birth_date,
    birth_time      = EXCLUDED.birth_time,
    birth_place     = EXCLUDED.birth_place,
    birth_lat       = EXCLUDED.birth_lat,
    birth_lon       = EXCLUDED.birth_lon,
    birth_tzone     = EXCLUDED.birth_tzone,
    gender          = EXCLUDED.gender,
    style           = EXCLUDED.style,
    focus           = EXCLUDED.focus,
    personalization = EXCLUDED.personalization,
    updated_at      = NOW()
RETURNING id, telegram_user_id, username, display_name, birth_date, birth_time, birth_place, birth_lat, birth_lon, birth_tzone, gender, style, focus, personalization, pro_status, pro_activated_at, trial_ends_at, sub_ends_at, push_enabled, created_at, updated_at
`

type UpsertUserParams struct {
	TelegramUserID  int64           `json:"telegram_user_id"`
	Username        *string         `json:"username"`
	DisplayName     *string         `json:"display_name"`
	BirthDate       time.Time       `json:"birth_date"`
	BirthTime       *string         `json:"birth_time"`
	BirthPlace      string          `json:"birth_place"`
	BirthLat        float64         `json:"birth_lat"`
	BirthLon        float64         `json:"birth_lon"`
	BirthTzone      float64         `json:"birth_tzone"`
	Gender          *string         `json:"gender"`
	Style           string          `json:"style"`
	Focus           string          `json:"focus"`
	Personalization json.RawMessage `json:"personalization"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.TelegramUserID,
		arg.Username,
		arg.DisplayName,
		arg.BirthDate,
		arg.BirthTime,
		arg.BirthPlace,
		arg.BirthLat,
		arg.BirthLon,
		arg.BirthTzone,
		arg.Gender,
		arg.Style,
		arg.Focus,
		arg.Personalization,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TelegramUserID,
		&i.Username,
		&i.DisplayName,
		&i.BirthDate,
		&i.BirthTime,
		&i.BirthPlace,
		&i.BirthLat,
		&i.BirthLon,
		&i.BirthTzone,
		&i.Gender,
		&i.Style,
		&i.Focus,
		&i.Personalization,
		&i.ProStatus,
		&i.ProActivatedAt,
		&i.TrialEndsAt,
		&i.SubEndsAt,
		&i.PushEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
