// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: void.sql

package db

import (
	"context"
	"time"
)

const decrementVoidCredits = `-- name: DecrementVoidCredits :exec
UPDATE void_credits
SET remaining = remaining - 1, updated_at = NOW()
WHERE user_id = $1 AND remaining > 0
`

func (q *Queries) DecrementVoidCredits(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, decrementVoidCredits, userID)
	return err
}

const deleteVoidEntry = `-- name: DeleteVoidEntry :exec
DELETE FROM void_history
WHERE user_id = $1 AND id = $2
`

type DeleteVoidEntryParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) DeleteVoidEntry(ctx context.Context, arg DeleteVoidEntryParams) error {
	_, err := q.db.Exec(ctx, deleteVoidEntry, arg.UserID, arg.ID)
	return err
}

const getVoidCredits = `-- name: GetVoidCredits :one
SELECT remaining, period_start, updated_at
FROM void_credits
WHERE user_id = $1
`

type GetVoidCreditsRow struct {
	Remaining   int32     `json:"remaining"`
	PeriodStart time.Time `json:"period_start"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) GetVoidCredits(ctx context.Context, userID int64) (GetVoidCreditsRow, error) {
	row := q.db.QueryRow(ctx, getVoidCredits, userID)
	var i GetVoidCreditsRow
	err := row.Scan(&i.Remaining, &i.PeriodStart, &i.UpdatedAt)
	return i, err
}

const getVoidEntry = `-- name: GetVoidEntry :one
SELECT id, user_id, question, answer, created_at
FROM void_history
WHERE user_id = $1 AND id = $2
`

type GetVoidEntryParams struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

func (q *Queries) GetVoidEntry(ctx context.Context, arg GetVoidEntryParams) (VoidHistory, error) {
	row := q.db.QueryRow(ctx, getVoidEntry, arg.UserID, arg.ID)
	var i VoidHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Question,
		&i.Answer,
		&i.CreatedAt,
	)
	return i, err
}

const insertVoidCredits = `-- name: InsertVoidCredits :exec
INSERT INTO void_credits (user_id, remaining, period_start)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO NOTHING
`

type InsertVoidCreditsParams struct {
	UserID      int64     `json:"user_id"`
	Remaining   int32     `json:"remaining"`
	PeriodStart time.Time `json:"period_start"`
}

func (q *Queries) InsertVoidCredits(ctx context.Context, arg InsertVoidCreditsParams) error {
	_, err := q.db.Exec(ctx, insertVoidCredits, arg.UserID, arg.Remaining, arg.PeriodStart)
	return err
}

const insertVoidEntry = `-- name: InsertVoidEntry :one
INSERT INTO void_history (user_id, question, answer)
VALUES ($1, $2, $3)
RETURNING id, user_id, question, answer, created_at
`

type InsertVoidEntryParams struct {
	UserID   int64  `json:"user_id"`
	Question string `json:"question"`
	Answer   string `json:"answer"`
}

func (q *Queries) InsertVoidEntry(ctx context.Context, arg InsertVoidEntryParams) (VoidHistory, error) {
	row := q.db.QueryRow(ctx, insertVoidEntry, arg.UserID, arg.Question, arg.Answer)
	var i VoidHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Question,
		&i.Answer,
		&i.CreatedAt,
	)
	return i, err
}

const listVoidHistory = `-- name: ListVoidHistory :many
SELECT id, user_id, question, answer, created_at
FROM void_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListVoidHistoryParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListVoidHistory(ctx context.Context, arg ListVoidHistoryParams) ([]VoidHistory, error) {
	rows, err := q.db.Query(ctx, listVoidHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoidHistory
	for rows.Next() {
		var i VoidHistory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Question,
			&i.Answer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshVoidCredits = `-- name: RefreshVoidCredits :exec
UPDATE void_credits
SET remaining = $2, period_start = $3, updated_at = NOW()
WHERE user_id = $1
`

type RefreshVoidCreditsParams struct {
	UserID      int64     `json:"user_id"`
	Remaining   int32     `json:"remaining"`
	PeriodStart time.Time `json:"period_start"`
}

func (q *Queries) RefreshVoidCredits(ctx context.Context, arg RefreshVoidCreditsParams) error {
	_, err := q.db.Exec(ctx, refreshVoidCredits, arg.UserID, arg.Remaining, arg.PeriodStart)
	return err
}
